config/routes.rb
Rails.application.routes.draw do


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root 'main#main'

    match 'auth/:provider/callback', to: 'session#create', via: [:get, :post]
    match 'auth/failure', to: redirect('/'), via: [:get, :post]
    match 'signout', to: 'session#destroy', as: 'signout', via: [:get, :post]
    match 'main1', to: 'main1#main1', as: 'main0', via: [:get, :post]
    match 'roads', to: 'road#roads', as: 'roads', via: [:get, :post]
    match 'road', to: 'road#index', as: 'road', via: [:get, :post]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

end

app/controllers/main1_controller.rb
class Main1Controller < ApplicationController
  def main
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def main
  end
end

app/controllers/road_controller.rb
class RoadController < ApplicationController
  def roads
  end
  def index
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    session[:user_uid] = user.uid

    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    session[:user_uid] = nil
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!-- Standard Meta -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

  <meta property="og:url"           content="http://www.gilwe.com/road?33" />
   <meta property="og:type"          content="website" />
   <meta property="og:title"         content="도를 찾아 가출하는 길" />
   <meta property="og:description"   content="모두가 함께 걸어 즐거운 서비스 길위!!" />
   <meta property="og:image"         content="/images/ff.png" />

  <!-- Site Properties -->
  <title>길위</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/semantic-ui/2.2.7/semantic.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!-- 자바스크립트 -->
    <script type="text/javascript" src="//apis.daum.net/maps/maps3.js?apikey=c90f108003e4d1ad38bb48d42174c722&libraries=drawing"></script>
    <script src="scripts/map.js" data-turbolinks-track="reload"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/semantic-ui/2.2.7/semantic.min.js"></script>
</head>
<body>


<div class="pusher">
  <div class="ui borderless main menu fixed" style="position: fixed; top: 0px; left: auto; z-index: 10;padding-top:50px;">
    <div class="ui text">
      <div class="header item">
        <img class="" src="/images/gilwe_icon.png" style="width:32px; height:32px;">
        <h2 style="margin:0px;">&nbsp;길위&nbsp;</h2> &nbsp;<p style="font-size:12px;">&nbsp;&nbsp; 길위에서 글을 읽다.</p>
      </div>
      </a>
    </div>
  </div>

  <!--
<div class="ui inverted vertical center aligned segment">

  <div class="ui container">
    <div class="ui large secondary inverted pointing menu">
      <a class="active item">        길위 (길을 담다 main)</a>
      <div class="right item">

        <!-- facebook Loginver1 S-->
          <!-- <% if current_user %>
            <span>
              <div class="ui horizontal list">
                <div class="item">
                  <img class="ui avatar image" src="https://graph.facebook.com/<%= current_user.uid %>/picture">
                  <div class="content">
                    <div class="ui sub header orange">일반 사용자</div>
                      <%= current_user.name %>
                  </div>
                </div>
              </div>
            </span>
            <%= link_to "Logout", signout_path, id: "sign_out", class: "ui inverted orange basic button"%>
          <% else %>
          <a href="/auth/facebook"><button class="ui facebook button"><i class="facebook icon"></i>Facebook</button></a>
          <% end %> -->
        <!--
      </div>
    </div>
  </div>
</div> -->


      <%= yield %>
      </div>

      <button class="ui circular orange plus icon button top">
        <i class="arrow up icon"></i>
      </button>

      <!-- <script>
        $(document).ready(function() {
          // jh: 헤더 메뉴
          $('.masthead').visibility({
              once: false,
              onBottomPassed: function() {
                $('.fixed.menu').transition('fade in');
              },
              onBottomPassedReverse: function() {
                $('.fixed.menu').transition('fade out');
              }
            });

          // create sidebar and attach to menu open
          $('.ui.sidebar').sidebar('attach events', '.toc.item');
        });
      </script>
      <div id="fb-root"></div> -->

</body>
</html>

app/views/main/main.html.erb
<div id="slider" style="position:relative; width:100%;white-space:nowrap;overflow:hidden; text-align: center;">
  <a href="#" id="prev2" class="prev"><img src="/images/btn_next_left.png" alt="이전"></a>
  <div class="slide-wrap">
    <ul id="photo" class="slide-list" style="width: 9990px; padding:0px;height:700px;">
      <li>
        <img src="/images/main_title_0.png" alt="">
      </li>
      <li>
        <img src="/images/main_title_1.png" alt="">
      </li>
      <li>
        <img src="/images/main_title_2.png" alt="">
      </li>
    </ul>
  </div>
  <a href="#" id="next2" class="next"><img src="/images/btn_next_right.png" alt="다음"></a>
</div>

</br>
<div class="ui container list_head" style="position:relative;">
    <h2 class="ui header">List</h2>


<div class="ui three column  grid container">
<a id="prev3" class="prev" onclick="fn_prev();"><img src="/images/next_left.png" alt="이전"></a>
  <div class="column">
    <div class="ui segment" style="padding:0px;">
      <div class="ui card">
        <div class="image">
          <img class="list_img" src="/images/main_0.png">
        </div>
      </div>
    </div>
    <div class="content">
      <span class="header floatLeft list_name" style="font-size:28px; top:5px;position:relative"><a href='/road/#33'>도를 찾아 가출하는 길</a></span>
      <span class="header floatRight"><img class="ui avatar userImg floatRight" src="https://graph.facebook.com/123242/picture"></span>
      <div class="description clearBoth list_info">
        1.8km |  25분 | 판교
      </div>
    </div>
  </div>

  <div class="column">
    <div class="ui segment" style="padding:0px;">
      <div class="ui card">
        <div class="image">
          <img class="list_img" src="/images/main_1.png">
        </div>
      </div>
    </div>
    <div class="content">
      <span class="header floatLeft list_name" style="font-size:28px; top:5px;position:relative"><a href='/road/#33'>같이 걸을래?</a></span>
      <span class="header floatRight"><img class="ui avatar userImg floatRight" src="https://graph.facebook.com/123345/picture"></span>
      <div class="description clearBoth list_info">
        5.3km | 1시간 20분 | 천안
      </div>
    </div>
  </div>

  <div class="column">
    <div class="ui segment" style="padding:0px;">
      <div class="ui card">
        <div class="image">
          <img class="list_img" src="/images/main_2.png">
        </div>
      </div>
    </div>
    <div class="content">
      <span class="header floatLeft list_name" style="font-size:28px; top:5px;position:relative"><a href='/road/#33'>바람쐬는 길</a></span>
      <span class="header floatRight"><img class="ui avatar userImg floatRight" src="https://graph.facebook.com/12345/picture"></span>
      <div class="description clearBoth list_info">
        1.3km | 50분 | 전주
      </div>
    </div>
  </div>
  <a id="next3" class="next" onclick="fn_next();"><img src="/images/next_right.png" alt="다음"></a>
</div>


<div class="ui vertical stripe segment">
<hr class="list_head">
</br>
    <table style="width:100%; border-collapse: collapse;  border-spacing: 0;">
      <tr>
        <td style="width:50%;border-collapse: collapse;  border-spacing: 0;">
          <h3 class="ui header">걷다.</h3>
          <h3 class="ui header">나만의 길을 걸으며, 그 길을 기록한다.</h3>
          </td>
        <td style="width:50%;border-collapse: collapse;  border-spacing: 0;">
          <img src="/images/main_3.png" style="width:100%; display:block">
        </td>
      </tr>
      <tr>
        <td style="width:50%;">
          <img src="/images/main_1.png" style="width:100%; display:block">
        </td>
        <td style="width:50%; padding-left:10px;">
          <h3 class="ui header">담다.</h3>
          <h3 class="ui header">내가 걷는 이 길 위에, 기억을 담아둔다.</h3>
        </td>
      </tr>
      <tr>
        <td style="width:50%;">
          <h3 class="ui header">잇다.</h3>
          <h3 class="ui header">누군가의 흔적을 따라, 그 길을 걷는다.</h3>
        </td>
        <td style="width:50%;">
          <img src="/images/main_2.png" style="width:100%; display:block">
        </td>
      </tr>

    </table>
  </div>
</div>

<div class="center aligned column" style="background-color:#e48f7a;padding-top:80px; padding-bottom:300px;">
  <div class="ui prebooking">
    <div class="ui" style="color:white;">
    <h2>내가 걷는 길 위에 추억을 남겨 보세요.</h2>
    <p>내가 걷는 길위에 추억을 남기고, 네가 걷던 길을 따라 걷는다.</p>
    <div class="ui right action input">
        <input type="email" placeholder="email을 주소를 등록하세요." style="width:450px;">
        <div class="ui orange button" style="background-color:#fca48e;" onclick="sendEmail();">
          <i class="add icon"></i>
          SUBMIT
        </div>
      </div>
    </div>
  </div>
</div>

<script src="/scripts/main.js"></script>

app/views/road/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>길위</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/semantic-ui/2.2.7/semantic.min.css">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <!-- 자바스크립트 -->
  <script type="text/javascript" src="//apis.daum.net/maps/maps3.js?apikey=c90f108003e4d1ad38bb48d42174c722&libraries=drawing"></script>
  <script src="/scripts/map.js" data-turbolinks-track="reload"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://cdn.jsdelivr.net/semantic-ui/2.2.7/semantic.min.js"></script>

  <link rel="stylesheet" href="https://fonts.googleapis.com/earlyaccess/nanumgothic.css">
  <link rel="stylesheet" href="/css/slide.css">
  <link rel="stylesheet" href="/css/index2.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<script src="scripts/jquery2.min.js"></script>
	<script src="scripts/jquery2.scrollex.min.js"></script>
	<script src="scripts/jquery2.scrolly.min.js"></script>
	<script src="scripts/skel2.min.js"></script>
	<script src="scripts/util2.js"></script>
	<!--[if lte IE 8]><script src="assets/js/ie/respond.min.js"></script><![endif]-->
	<script src="/scripts/main2.js"></script>
</head>
<body>
  <div class="contents_first" style="padding-top:120px">
      <!-- title, 총거리, 시간, 지역 -->
      <div class="" style="width:1080px; margin: 0 auto;">
          <div class="contents_main">
              <div class="first_items" id="contents_icon">
                  <img class="ui avatar image" style="margin-top:6px;" src="https://graph.facebook.com/12345/picture">
              </div>
              <div class="first_items">
                  <div class="first_items_items" id="contents_title">
                      <span style="font-size:17px;">도를 찾아 가출 하는 길</span>
                  </div>
                  <div class="first_items_items">
                      <div class="first_items_items_items" id="contents_distance">1.8km</div>
                      <div class="first_items_items_items" id="contents_time">25분</div>
                      <div class="first_items_items_items" id="contents_region">판교</div>
                      <div class="first_items_items_items"></div>
                  </div>
              </div>
              <div class="first_items">
              </div>
          </div>

          <div class="map_image">
              <div class="" id="" style="padding-right:5px;">
                  <img src="/images/ff.jpg" class="second_items_items"style='width:656px; height:390px;' alt=""/>
              </div>
              <div class="second_items" id="map"></div>

          </div>
      </div>
  </div>

  <div class="contents_second">
      <div class=""style="width:1080px;  margin: 0 auto;">
          <div class="spot_info">
              <img class="icon_map" src="/images/gallery/fulls/icon_map_tag.png"/>
              <div class="spot_number">7</div>
              <div class="second_distance">0.00km</div>
          </div>
          <div class="gallery style2 medium lightbox onscroll-fade-in" style="padding-top: 41px;">
      		<article>
      			<a href="/images/31.jpg" class="image">
      				<img class="slide_image" src="/images/31.jpg" alt="도촬 ㅋㅋㅋㅋ" />
      			</a>
      		</article>
      		<article>
      			<a href="/images/32.jpg" class="image">
      				<img class="slide_image" src="/images/32.jpg" alt="좋단다~ㅋㅋㅋ" />
      			</a>
      		</article>
      		<article>
      			<a href="/images/ff.jpg" class="image">
      				<img class="slide_image" src="/images/ff.jpg" alt="먹어야 산다.!" />
      			</a>
      		</article>
      		<article>
      			<a href="/images/34.jpg" class="image">
      				<img class="slide_image" src="/images/34.jpg" alt="양?아치???" />
      			</a>
      		</article>
      		<article>
      			<a href="/images/35.jpg" class="image">
      				<img class="slide_image" src="/images/36.jpg" alt="멀더라 스타벅스.ㅠㅠ" />
      			</a>
      		</article>
      		<article>
      			<a href="/images/37.jpg" class="image">
      				<img class="slide_image" src="/images/37.jpg" alt="동네형들 입장중.." />
      			</a>
      		</article>

      	</div>
      	<div class="spot_info">
              <img class="icon_map" src="/images/gallery/fulls/icon_map_tag.png"/>
              <div class="spot_number">6</div>
              <div class="second_distance">1.00km</div>
          </div>
          <div class="gallery style2 medium lightbox onscroll-fade-in" style="padding-top: 41px;">
      		<article>
      			<a href="/images/40.jpg" class="image">
      				<img class="slide_image" src="/images/40.jpg" alt="" />
      			</a>
      		</article>
      		<article>
      			<a href="/images/41.jpg" class="image">
      				<img class="slide_image" src="/images/41.jpg" alt="" />
      			</a>
      		</article>
      		<article>
      			<a href="/images/42.jpg" class="image">
      				<img class="slide_image" src="/images/42.jpg" alt="" />
      			</a>
      		</article>
      		<article>
      			<a href="/images/43.jpg" class="image">
      				<img class="slide_image" src="/images/43.jpg" alt="" />
      			</a>
      		</article>
      		<article>
      			<a href="/images/44.jpg" class="image">
      				<img class="slide_image" src="/images/44.jpg" alt="" />
      			</a>
      		</article>
      		<article>
      			<a href="/images/45.jpg" class="image">
      				<img class="slide_image" src="/images/45.jpg" alt="" />
      			</a>
      		</article>

      	</div>
      </div>
  </div>

  <!-- <script>
  var mapContainer = document.getElementById('map'), // 지도를 표시할 div
      mapOption = {
          center: new daum.maps.LatLng(33.452739313807456, 126.5709308145358), // 지도의 중심좌표
          level: 3 // 지도의 확대 레벨
      };

  var map = new daum.maps.Map(mapContainer, mapOption); // 지도를 생성합니다

  // 선을 구성하는 좌표 배열입니다. 이 좌표들을 이어서 선을 표시합니다
  var linePath = [
      new daum.maps.LatLng(33.452344169439975, 126.56878163224233),
      new daum.maps.LatLng(33.452739313807456, 126.5709308145358),
      new daum.maps.LatLng(33.45178067090639, 126.5726886938753)
  ];

  // 지도에 표시할 선을 생성합니다
  var polyline = new daum.maps.Polyline({
      path: linePath, // 선을 구성하는 좌표배열 입니다
      strokeWeight: 5, // 선의 두께 입니다
      strokeColor: '#FFAE00', // 선의 색깔입니다
      strokeOpacity: 0.7, // 선의 불투명도 입니다 1에서 0 사이의 값이며 0에 가까울수록 투명합니다
      strokeStyle: 'solid' // 선의 스타일입니다
  });

  // 지도에 선을 표시합니다
  polyline.setMap(map);
  </script> -->
</br>
</br>
</br>
  <div class="center aligned column" style="background-color:#e48f7a;padding-top:80px; padding-bottom:300px;">
    <div class="ui prebooking">
      <div class="ui" style="color:white;">
      <h2>내가 걷는 길 위에 추억을 남겨 보세요.</h2>
      <p>내가 걷는 길위에 추억을 남기고, 네가 걷던 길을 따라 걷는다.</p>
      <div class="ui right action input">
          <input type="email" placeholder="email을 주소를 등록하세요." style="width:450px;">
          <div class="ui orange button" style="background-color:#fca48e;" onclick="sendEmail();">
            <i class="add icon"></i>
            SUBMIT
          </div>
        </div>
      </div>
    </div>
  </div>


  <script>

  // var map = '{"name": "Running 2/24/17 7:17 pm","time": "2017-02-24T10:17:51Z"}';
  //var dummy = '{"name": "Running 2/24/17 7:17 pm",  "time": "2017-02-24T10:17:51Z",      "locations": [        {       "lat": "37.464299000","lng": "127.030405000",  "ele": "26.8",    "time": "2017-02-24T10:17:51Z"    },    {       "lat": "37.467569000",       "lng": "127.029118000",       "ele": "26.4",       "time": "2017-02-24T10:28:08Z"     },     {       "lat": "37.470549000",       "lng": "127.031328000",      "ele": "25.6",       "time": "2017-02-24T10:38:31Z"      },     {       "lat": "37.471928000",       "lng": "127.032766000",       "ele": "25.0",       "time": "2017-02-24T10:43:53Z"     },     {       "lat": "37.473087000",       "lng": "127.034482000",       "ele": "25.0",     "time": "2017-02-24T10:49:16Z"     },    {      "lat": "37.473819000",      "lng": "127.037637000",      "ele": "25.0",       "time": "2017-02-24T10:57:05Z"    },     {      "lat": "37.474670000",   "lng": "127.039976000",     "ele": "24.0",       "time": "2017-02-24T11:03:13Z"     },     {       "lat": "37.476680000",      "lng": "127.041864000",       "ele": "24.4",     "time": "2017-02-24T11:10:45Z"     },     {       "lat": "37.478655000",       "lng": "127.043495000",       "ele": "23.8",       "time": "2017-02-24T11:17:51Z"     }   ]}';


var jsonDummy2 = '{"locations":[{"lat": "37.404085000","lng": "127.106409000"},{"lat": "37.403296000","lng": "127.106494000"},{"lat": "37.402431000",  "lng": "127.106527000"},  {  "lat": "37.402414000",  "lng": "127.107626000"},{    "lat": "37.401920000",    "lng": "127.107766000"  },  {    "lat": "37.401562000",    "lng": "127.107739000"  }, {   "lat": "37.400592000",   "lng": "127.107739000" }, {   "lat": "37.399866000",    "lng": "127.107696000"  },  {    "lat": "37.399849000",    "lng": "127.108404000"  },  {    "lat": "37.400540000",    "lng": "127.108436000"  },  {    "lat": "37.400897000",    "lng": "127.108436000"  },  {    "lat": "37.400948000",    "lng": "127.109638000"  },  {    "lat": "37.403931000",    "lng": "127.109659000"  },  {    "lat": "37.403965000",    "lng": "127.106537000"  }]}'

  var jsonDummy = $.parseJSON(jsonDummy2);
  var locations =  jsonDummy.locations;
  var path = new Array();
     var locaLeng = locations.length;

     for(var i=0; i < locaLeng; i++){
       path.push(new daum.maps.LatLng(locations[i].lat, locations[i].lng));
     }

  fn_draw_line(fn_draw_map('map', locations[4].lat, locations[4].lng), path);


  function sendEmail(){
    alert(
      '사전등록이 완료되었습니다.'
    );
  }

  </script>
</body>

</html>

app/views/road/roads.html.erb
<div class="ui container" style="padding-top:70px; padding-bottom:70px;">

<div class="ui secondary pointing menu">
  <a class="active item">
    <h2 class="ui header">List</h2>
  </a>
</div>

<div class="ui three column  grid container">

<div class="column">
  <div class="ui segment" style="padding:0px;">
    <div class="ui card">
      <div class="image">
        <img src="http://www.koreabrazil.net/n_comu/data/tmp/cg4LGGHXkNp5.jpg">
      </div>
      <div class="content">
        <a class="header">Kristy
          <span class="right floated">
            <img class="ui avatar image" src="https://graph.facebook.com/12345/picture">
          </span>
        </a>
        <div class="meta">
          <span class="date"></span>
        </div>
        <div class="description">
          총거리 | 총시간 | 지역
        </div>
      </div>
    </div>
  </div>
</div>

<div class="column">
  <div class="ui segment" style="padding:0px;">
    <div class="ui card">
      <div class="image">
        <img src="http://www.koreabrazil.net/n_comu/data/tmp/cg4LGGHXkNp5.jpg">
      </div>
      <div class="content">
        <a class="header">Kristy
          <span class="right floated">
            <img class="ui avatar image" src="https://graph.facebook.com/12345/picture">
          </span>
        </a>
        <div class="meta">
          <span class="date"></span>
        </div>
        <div class="description">
          총거리 | 총시간 | 지역
        </div>
      </div>
    </div>
  </div>
</div>

<div class="column">
  <div class="ui segment" style="padding:0px;">
    <div class="ui card">
      <div class="image">
        <img src="http://www.koreabrazil.net/n_comu/data/tmp/cg4LGGHXkNp5.jpg">
      </div>
      <div class="content">
        <a class="header">Kristy
          <span class="right floated">
            <img class="ui avatar image" src="https://graph.facebook.com/12345/picture">
          </span>
        </a>
        <div class="meta">
          <span class="date"></span>
        </div>
        <div class="description">
          총거리 | 총시간 | 지역
        </div>
      </div>
    </div>
  </div>
</div>

<div class="column">
  <div class="ui segment" style="padding:0px;">
    <div class="ui card">
      <div class="image">
        <img src="http://www.koreabrazil.net/n_comu/data/tmp/cg4LGGHXkNp5.jpg">
      </div>
      <div class="content">
        <a class="header">Kristy
          <span class="right floated">
            <img class="ui avatar image" src="https://graph.facebook.com/12345/picture">
          </span>
        </a>
        <div class="meta">
          <span class="date"></span>
        </div>
        <div class="description">
          총거리 | 총시간 | 지역
        </div>
      </div>
    </div>
  </div>
</div>

<div class="column">
  <div class="ui segment" style="padding:0px;">
    <div class="ui card">
      <div class="image">
        <img src="http://www.koreabrazil.net/n_comu/data/tmp/cg4LGGHXkNp5.jpg">
      </div>
      <div class="content">
        <a class="header">Kristy
          <span class="right floated">
            <img class="ui avatar image" src="https://graph.facebook.com/12345/picture">
          </span>
        </a>
        <div class="meta">
          <span class="date"></span>
        </div>
        <div class="description">
          총거리 | 총시간 | 지역
        </div>
      </div>
    </div>
  </div>
</div>



</div>
</div>

<div class="center aligned column" style="background-color:#e48f7a;padding-top:80px; padding-bottom:300px;">
  <div class="ui prebooking">
    <div class="ui" style="color:white;">
    <h2>내가 걷는 길 위에 추억을 남겨 보세요.</h2>
    <p>내가 걷는 길위에 추억을 남기고, 네가 걷던 길을 따라 걷는다.</p>
    <div class="ui right action input">
        <input type="text" placeholder="email을 주소를 등록하세요." style="width:450px;">
        <div class="ui orange button" style="background-color:#fca48e;">
          <i class="add icon"></i>
          SUBMIT
        </div>
      </div>
    </div>
  </div>
</div>


<script src="/assets/road.js" data-turbolinks-track="reload"></script>